### PR TITLE
Release roll

### PR DESCRIPTION
**Pull request by fireice-uk**
@psychocrypt can you sign this off as ready for release?

### CODE REVIEW

**Comment by fireice-uk** [comment]
Also if you confirm if https://github.com/fireice-uk/xmr-stak-amd/pull/17 should be merged before or put on hold (you never got back to me on that one)

**Comment by psychocrypt** [comment]
#17 shuld be delayed until the issue is solved.  There was no time for deeper investigation in the past.

The best way to release would be to create a release candidate branch and change the versiin number there. 
I will open a branch and than I will test the branch again and you could create the windows binaries and change the hash there. After everything is ready we need only to merge it to master and after that I willupdate the dev with the change from the master.

**Comment by fireice-uk** [comment]
Ok, can you have a look at https://github.com/fireice-uk/xmr-stak-cpu/pull/126 - I think it might be good to include that in the release here too.

**Comment by psychocrypt** [comment]
OK I will check the pull request.
- we should than push a new PR to this dev with  https://github.com/fireice-uk/xmr-stak-cpu/pull/126
- I will cherry pick the PR to the the rc branch

**Comment by psychocrypt** [comment]
I close this PR because we have now #27 for the release

**Pull request closed without merging**
