### PR TITLE
increase default dev donation

### PR DESCRIPTION
**Pull request by psychocrypt**
based on the [reddit poll](https://www.reddit.com/r/MoneroMining/comments/6eu00j/question_xmrstak_default_donation_increase_to_2/) we get 45.99% support to increase the developer donation

poll_dev_donation

### CODE REVIEW

**Comment by Panzerfather** [comment]
Just a sidenote about miner dev donations: wouldn't it make sense to directly collaborate with mining pools that they paying out a donation directly to the miner software maintainers?

So the devs of this and all other miners will be supported fairly with a small amount for each accepted share (based on PPS/PPLNS models) and the maintainers aren't dependent from mining on there own pools and maintaining them additionally to the mining software.

As example:

Form [node-cryptonote-pool](https://github.com/zone117x/node-cryptonote-pool) the project where most of the pool servers for cryptonight currencies depends on, they already can make donations to the devs of the currency.

```
/* Module that monitors the submitted block maturities and manages rounds. Confirmed
   blocks mark the end of a round where workers' balances are increased in proportion
   to their shares. */
"blockUnlocker": {
    "enabled": true,
    "interval": 30, //how often to check block statuses in seconds

    /* Block depth required for a block to unlocked/mature. Found in daemon source as
       the variable CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW */
    "depth": 60,
    "poolFee": 1.8, //1.8% pool fee (2% total fee total including donations)
    "devDonation": 0.1, //0.1% donation to send to pool dev - only works with Monero
    "coreDevDonation": 0.1 //0.1% donation to send to core devs - only works with Monero
},
```
So why not make an extension to the pool like this (values are only examples):

```
/* Module that monitors the submitted block maturities and manages rounds. Confirmed
   blocks mark the end of a round where workers' balances are increased in proportion
   to their shares. */
"blockUnlocker": {
    "enabled": true,
    "interval": 30, //how often to check block statuses in seconds

    /* Block depth required for a block to unlocked/mature. Found in daemon source as
       the variable CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW */
    "depth": 60,
    "poolFee": 1.8, //1.8% pool fee (2.001% total fee total including donations)
    "devDonation": 0.1, //0.1% donation to send to pool dev - only works with Monero
    "coreDevDonation": 0.1 //0.1% donation to send to core devs - only works with Monero
    "minerDonation": 0.001 //0.01% miner software donation for each share the user was payed out to send to the miner devs
},
```

As the login command already submits the miner name to the pool, we even don't change or extend the protocol for that.
```
bool jpsock::cmd_login(const char* sLogin, const char* sPassword)
{
	char cmd_buffer[1024];

	snprintf(cmd_buffer, sizeof(cmd_buffer), "{\"method\":\"login\",\"params\":{\"login\":\"%s\",\"pass\":\"%s\",\"agent\":\"" AGENTID_STR "\"},\"id\":1}\n",
		sLogin, sPassword);

	opq_json_val oResult(nullptr);

	/*Normal error conditions (failed login etc..) will end here*/
	if (!cmd_ret_wait(cmd_buffer, oResult))
		return false;

	if (!oResult.val->IsObject())
	{
		set_socket_error("PARSE error: Login protocol error 1");
		disconnect();
		return false;
	}

	const Value* id = GetObjectMember(*oResult.val, "id");
	const Value* job = GetObjectMember(*oResult.val, "job");

	if (id == nullptr || job == nullptr || !id->IsString())
	{
		set_socket_error("PARSE error: Login protocol error 2");
		disconnect();
		return false;
	}

	if (id->GetStringLength() >= sizeof(sMinerId))
	{
		set_socket_error("PARSE error: Login protocol error 3");
		disconnect();
		return false;
	}

	memset(sMinerId, 0, sizeof(sMinerId));
	memcpy(sMinerId, id->GetString(), id->GetStringLength());

	opq_json_val v(job);
	if(!process_pool_job(&v))
	{
		disconnect();
		return false;
	}

	bLoggedIn = true;

	return true;
}
```

Just extend the `AGENTID_STR ` value e.g. like this:

`#define AGENTID_STR XMR_STAK_NAME "/" XMR_STAK_VERSION "@" XMR_STAK_DEVDONATIONADDRESS`

In the end the pool have only to calculate the donation for each mining software which were active for the calculation of this block and payout them directly in their dev wallet. As this calculation took already place to payout the miner users, this wouldn't be hard to implement on the pool software. As then every miner would pay a very, very, very small amount this would raise the dev donations without raising the dev pool mining period. As all miner software users will give a donation for the free use of the software, the earnings should be greater than now, even with a raised dev pool donation.

And in the end, this (can) also lead to make the (hard-)coded dev donation values obsolete and also the code to switch the pools in the mining software and clean the code and speed it up (probably in a immeasurable) amount. And the dev team would get more time to focus on the development because they wouldn't need to run and maintain their own pool (in this case donate.xmr-stak.net) and don't have to pay bills for their own pool server.

So as a summary the advantages for the devs would be:
- removal of dev pool code and so smaller code size to maintain
- don't need to run, maintain and pay for own dev pool
- higher donation rate as every miner is donating a (very) small amount which result in a higher end amount

And for the user:
- Full mining power for there selected pool
- Have no feeling of loosing time/money while donating the developers
- More chances that the developers put more time into this free project as they will earn more than now

What do you guys (@fireice-uk, @psychocrypt) think about this?

**Comment by psychocrypt** [comment]
The idea is good but not possible to integrate. First all pools need to support it what will never work. 

> Have no feeling of loosing time/money while donating the developers

If someone has the feeling that he/she is loosing money than there are two options, switch to another miner or change the donation.

Currently the miner is independent and the miner devs must not trust the pools. Another point is that it is possible to use the miner directly with a proxy and the original monero deamon to mine without a pool, in that case the dev still get the configuard donation.

2% donation will not create a much hashing power if you spread it over many pools the donation per pool would be extrem small and mybe never payed out.

**Comment by Panzerfather** [comment]
Just to make one thing crystal clear, I'm/we (my company) are not against dev donations at all or against the raised value. We are fine and the changes will help both of you supporting this application.

Just a clarification what we meant when writing

> Have no feeling of loosing time/money while donating the developers

The situation behind this is because of the following:

When the end user is optimizing his machine for the last 1-5% to get more output from it, he also easily comes to the conclusion that when disabling the dev donations he/she will get even 1% and now 2% more calculation power for himself. And without having in mind that the devs for this application will only working/optimizing the code for him/her when receiving an appropriate amount for their work, this is looking fine for them so in the end they are just disabling the dev donations at all. 😞 

But most of these users have no problem with paying appropriate fees for the mining pools when they working flawless. Of course they are searching for low fee pools, but choose the one were the fee to secure payout+performance+options ratio feels the best for them. So a pool with 1.5% may let them feel better while on the software side they search for 0.1% more performance. And a fee low miner dev donation fee won't disturb them at all.

So with our suggestion we just wanted to inspire and show another way than implementing it via code as we think that there are (too) many concerns from a wide user base when they have to give there time consumed optimized CPU/GPU power to "others". 

And now to your raised concerns:

> If someone has the feeling that he/she is loosing money than there are two options, switch to another miner or change the donation.

Such end users are looking for the best miner to fit for their situation, but as pointed out above he/she won't think what will happen when disabling the donations. (Take a look at all aborted miner applications)

> Currently the miner is independent and the miner devs must not trust the pools.

Crystal clear, but the miner devs must trust the end users. So the trusting situation will be the same, but trustful pools will also pay out the donations to the devs.

> Another point is that it is possible to use the miner directly with a proxy and the original monero deamon to mine without a pool, in that case the dev still get the configuard donation.

Do you have a clue how much miner(=users) doing this with so high difficulty? Are these values higher or lower than the user base which is disabling the dev donations?

> 2% donation will not create a much hashing power if you spread it over many pools the donation per pool would be extrem small and mybe never payed out.

Of course you will have to reach the minimum payout level before receiving the donations but that's the same situation as for the currency dev donations which are already implemented in all the pools and activated in trustworthy pools. So you would receive your donations a little bit later as right now, but will receive them even when the users disabled the dev donation in the application.

Just a small calculation example while receiving a 0.01% miner dev fee from a ~10MH/sec monero pool and a 3 day payout ratio of 815 XMR/day and 243 miner payouts/day:

815 XMR * 0.01% / 243 = 0,000335391 XMR / day / miner

So when you only assume that only 10% of the miners where using xmr-stak-[amd|cpu|nvidia] in this example you would reveive 0,003353909 XMR / day for this pool only. Current monero network pool hashrate are ~90 MH/sec so dev donations per day would be much higher (factor 9 as optimum) and I also assume that xmr-stak-[amd|cpu|nvidia] is used in a larger base than 10%. Currently there are 10 cryptonote/cryptonight currencies so possible daily earnings will also be higher than in this example.

And last but not least, have you in mind what you will do if the difficulty will raise in the future with the current dev pool model integrated in the application? What actions will you have to do to make sure that earnings be the same as right now?

**Comment by psychocrypt** [comment]
> And last but not least, have you in mind what you will do if the difficulty will raise in the future with the current dev pool model integrated in the application? What actions will you have to do to make sure that earnings be the same as right now?

Thats a easy question 2% are 2% independent of the difficulty. There will be no benefit if the donation is collected by the pool. Because the miner dev will still donate only if there miner is used and proportional to the usage and if the donation is not disabled.
The pool model has also a negative effect to new developer those forking a project and than start. If all hash rate is going to one developer address on one pool the start is much easier. Not every miner will get as popular as @fireice-uk's miner.

I can't see a advantage for the miner develeoper but I will read all your point today again.

**Comment by Panzerfather** [comment]
@psychocrypt 

> The pool model has also a negative effect to new developer those forking a project and than start. If all hash rate is going to one developer address on one pool the start is much easier.

But isn't the pool model not easier for forks to handle as they only need to change the donation address instead of running and maintaining there own dev pool? And could this not being used to also support the main developers the fork is coming from?

e.g.

`#define AGENTID_STR XMR_STAK_NAME "/" XMR_STAK_VERSION "@" XMR_STAK_DEVDONATIONADDRESS#FORKDONATIONADDRESS`

> Not every miner will get as popular as @fireice-uk's miner.

That's true, but doesn't this mean that the forked dev pool doesn't even payout as there is not much traffic there to create a block?

> ... but I will read all your point today again.

You don't need to hurry up, take your time whenever you can. This isn't time critical at the moment. Just an idea to be worked out.

**Comment by xmrig** [comment]
Dev pool not mean a true pool, it can be proxy to other pool or pools, anything, fully flexibility.

**Comment by Panzerfather** [comment]
@xmrig Yes you are right, didn't thought about proxies were you didn't need to setup a full pool, but you also don't earn your full donation amount. Either you have to share it with all other miners on the pool(s) or for proxies when "payday" has arrived you have to pay fees for the payout. So this creates the same situation like using the pool model directly, won't it?

All of the possibilities took fees except the direct mining with a crypto currency daemon like (monerod for Monero) but this becomes an exclusively "private service model" when a currency became popular and also needs maintenance and attention to run.

**Pull request merged**
