### PR TITLE
release 1.4.0

### PR DESCRIPTION
**Pull request by psychocrypt**
This branch is the release candidate for xmr-stak-amd 1.4.0.

## TODO

- [x] runtime/ compile Tests
- [x] change version to 1.4.0
- [ ] update README.txt with the windows sha's

### CODE REVIEW

**Comment by psychocrypt** [comment]
@fireice-uk Please update in this pull request everything you normally do for the release. 
If you are ready please merge this branch to master and create a tag out of the master.
I will merge the master back to dev.

**Comment by fireice-uk** [comment]
Ok. Great. Thanks for the assist :)

Versioning convention that I have is to have the core version increase only when speed improvements are made. Should this be 1.0.1-1.4.0 or 1.1.0-1.4.0

**Comment by psychocrypt** [comment]
There is a speed increase with #35. But also other improvements are impotent e.g. the demon mode.

In the most software the last number is increased if a bug is fixed but no improvements are coming in.
The second number is changed if new improvements are made.

But feel free to change the version number!

What means *1.1.0-*1.4.0? Could you please give me a short introduction in  your versioning.

**Comment by fireice-uk** [comment]
Versioning is simple - first number is for the miner core the second is for the stak features. So a bugfix to the core will start with 1.0.1 while a speed improvement 1.1.0

**Comment by psychocrypt** [comment]
Thx for the description. We should update version.hpp to show both version numbers too.

**Comment by fireice-uk** [comment]
Pushed daemon mode cherry-pick here. More incoming as I roll the release

**Comment by fireice-uk** [comment]
@psychocrypt The official release version will be 1.1.0-1.4.0 - we didn't include the other stak's 1.4 feature (autoconfig) here yet, we will need to decide what to do about that.

**Comment by fireice-uk** [comment]
@psychocrypt can you verify pre-release packages to make sure I didn't forget something silly (like config.txt last time)?

[xmr-stak-amd-notls-win64.zip](https://github.com/fireice-uk/xmr-stak-amd/files/1034068/xmr-stak-amd-notls-win64.zip)
[xmr-stak-amd-win64.zip](https://github.com/fireice-uk/xmr-stak-amd/files/1034067/xmr-stak-amd-win64.zip)

**Comment by psychocrypt** [comment]
will reviee and test it tonight

**Comment by psychocrypt** [comment]
I tested both binaries. Both are running fine under my Win7(64bit)
IMO we should change the default config to one gpu and invinity of 512 to be compatible to the most systems.
Someone with a rig of more than one GPUs will have no problem to change the config to support more GPUs but someone with a default PC with a AMD graphic card and the current default config.txt will have problems to get xmr-stak-amd running.

This is only a suggestion and no must have.

**Comment by fireice-uk** [comment]
@psychocrypt Let's do it in a PR and a new version. Will merge this one and get the show on the road (sorry it slipped my mind earlier this week)

**Comment by psychocrypt** [comment]
No problem we can move it to the next release.

Have you updated the sha in the readme for the current release?

**Comment by fireice-uk** [comment]
Yes, that was in 93a9297

**Pull request merged**
